/*
 * Copyright (C) 2026 Recep Aslantas
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include "../common.h"

static const VkFormat vk_formats[GPU_FORMAT_COUNT] = {
  [GPU_FORMAT_R8_UNORM]                    = VK_FORMAT_R8_UNORM,
  [GPU_FORMAT_R8_SNORM]                    = VK_FORMAT_R8_SNORM,
  [GPU_FORMAT_R8_UINT]                     = VK_FORMAT_R8_UINT,
  [GPU_FORMAT_R8_SINT]                     = VK_FORMAT_R8_SINT,
  [GPU_FORMAT_R16_UNORM]                   = VK_FORMAT_R16_UNORM,
  [GPU_FORMAT_R16_SNORM]                   = VK_FORMAT_R16_SNORM,
  [GPU_FORMAT_R16_UINT]                    = VK_FORMAT_R16_UINT,
  [GPU_FORMAT_R16_SINT]                    = VK_FORMAT_R16_SINT,
  [GPU_FORMAT_R16_FLOAT]                   = VK_FORMAT_R16_SFLOAT,
  [GPU_FORMAT_RG8_UNORM]                   = VK_FORMAT_R8G8_UNORM,
  [GPU_FORMAT_RG8_SNORM]                   = VK_FORMAT_R8G8_SNORM,
  [GPU_FORMAT_RG8_UINT]                    = VK_FORMAT_R8G8_UINT,
  [GPU_FORMAT_RG8_SINT]                    = VK_FORMAT_R8G8_SINT,
  [GPU_FORMAT_R32_UINT]                    = VK_FORMAT_R32_UINT,
  [GPU_FORMAT_R32_SINT]                    = VK_FORMAT_R32_SINT,
  [GPU_FORMAT_R32_FLOAT]                   = VK_FORMAT_R32_SFLOAT,
  [GPU_FORMAT_RG16_UNORM]                  = VK_FORMAT_R16G16_UNORM,
  [GPU_FORMAT_RG16_SNORM]                  = VK_FORMAT_R16G16_SNORM,
  [GPU_FORMAT_RG16_UINT]                   = VK_FORMAT_R16G16_UINT,
  [GPU_FORMAT_RG16_SINT]                   = VK_FORMAT_R16G16_SINT,
  [GPU_FORMAT_RG16_FLOAT]                  = VK_FORMAT_R16G16_SFLOAT,
  [GPU_FORMAT_RGBA8_UNORM]                 = VK_FORMAT_R8G8B8A8_UNORM,
  [GPU_FORMAT_RGBA8_UNORM_SRGB]            = VK_FORMAT_R8G8B8A8_SRGB,
  [GPU_FORMAT_RGBA8_SNORM]                 = VK_FORMAT_R8G8B8A8_SNORM,
  [GPU_FORMAT_RGBA8_UINT]                  = VK_FORMAT_R8G8B8A8_UINT,
  [GPU_FORMAT_RGBA8_SINT]                  = VK_FORMAT_R8G8B8A8_SINT,
  [GPU_FORMAT_BGRA8_UNORM]                 = VK_FORMAT_B8G8R8A8_UNORM,
  [GPU_FORMAT_BGRA8_UNORM_SRGB]            = VK_FORMAT_B8G8R8A8_SRGB,
  [GPU_FORMAT_RGB10A2_UNORM]               = VK_FORMAT_A2B10G10R10_UNORM_PACK32,
  [GPU_FORMAT_RGB10A2_UINT]                = VK_FORMAT_A2B10G10R10_UINT_PACK32,
  [GPU_FORMAT_RG11B10_UFLOAT]              = VK_FORMAT_B10G11R11_UFLOAT_PACK32,
  [GPU_FORMAT_RGB9E5_UFLOAT]               = VK_FORMAT_E5B9G9R9_UFLOAT_PACK32,
  [GPU_FORMAT_RG32_UINT]                   = VK_FORMAT_R32G32_UINT,
  [GPU_FORMAT_RG32_SINT]                   = VK_FORMAT_R32G32_SINT,
  [GPU_FORMAT_RG32_FLOAT]                  = VK_FORMAT_R32G32_SFLOAT,
  [GPU_FORMAT_RGBA16_UNORM]                = VK_FORMAT_R16G16B16A16_UNORM,
  [GPU_FORMAT_RGBA16_SNORM]                = VK_FORMAT_R16G16B16A16_SNORM,
  [GPU_FORMAT_RGBA16_UINT]                 = VK_FORMAT_R16G16B16A16_UINT,
  [GPU_FORMAT_RGBA16_SINT]                 = VK_FORMAT_R16G16B16A16_SINT,
  [GPU_FORMAT_RGBA16_FLOAT]                = VK_FORMAT_R16G16B16A16_SFLOAT,
  [GPU_FORMAT_RGBA32_UINT]                 = VK_FORMAT_R32G32B32A32_UINT,
  [GPU_FORMAT_RGBA32_SINT]                 = VK_FORMAT_R32G32B32A32_SINT,
  [GPU_FORMAT_RGBA32_FLOAT]                = VK_FORMAT_R32G32B32A32_SFLOAT,
  [GPU_FORMAT_BC1_RGBA_UNORM]              = VK_FORMAT_BC1_RGBA_UNORM_BLOCK,
  [GPU_FORMAT_BC1_RGBA_UNORM_SRGB]         = VK_FORMAT_BC1_RGBA_SRGB_BLOCK,
  [GPU_FORMAT_BC2_RGBA_UNORM]              = VK_FORMAT_BC2_UNORM_BLOCK,
  [GPU_FORMAT_BC2_RGBA_UNORM_SRGB]         = VK_FORMAT_BC2_SRGB_BLOCK,
  [GPU_FORMAT_BC3_RGBA_UNORM]              = VK_FORMAT_BC3_UNORM_BLOCK,
  [GPU_FORMAT_BC3_RGBA_UNORM_SRGB]         = VK_FORMAT_BC3_SRGB_BLOCK,
  [GPU_FORMAT_BC4_R_UNORM]                 = VK_FORMAT_BC4_UNORM_BLOCK,
  [GPU_FORMAT_BC4_R_SNORM]                 = VK_FORMAT_BC4_SNORM_BLOCK,
  [GPU_FORMAT_BC5_RG_UNORM]                = VK_FORMAT_BC5_UNORM_BLOCK,
  [GPU_FORMAT_BC5_RG_SNORM]                = VK_FORMAT_BC5_SNORM_BLOCK,
  [GPU_FORMAT_BC6H_RGB_FLOAT]              = VK_FORMAT_BC6H_SFLOAT_BLOCK,
  [GPU_FORMAT_BC6H_RGB_UFLOAT]             = VK_FORMAT_BC6H_UFLOAT_BLOCK,
  [GPU_FORMAT_BC7_RGBA_UNORM]              = VK_FORMAT_BC7_UNORM_BLOCK,
  [GPU_FORMAT_BC7_RGBA_UNORM_SRGB]         = VK_FORMAT_BC7_SRGB_BLOCK,
  [GPU_FORMAT_EAC_R11_UNORM]               = VK_FORMAT_EAC_R11_UNORM_BLOCK,
  [GPU_FORMAT_EAC_R11_SNORM]               = VK_FORMAT_EAC_R11_SNORM_BLOCK,
  [GPU_FORMAT_EAC_RG11_UNORM]              = VK_FORMAT_EAC_R11G11_UNORM_BLOCK,
  [GPU_FORMAT_EAC_RG11_SNORM]              = VK_FORMAT_EAC_R11G11_SNORM_BLOCK,
  [GPU_FORMAT_ETC2_RGBA8_UNORM]             = VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK,
  [GPU_FORMAT_ETC2_RGBA8_UNORM_SRGB]        = VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK,
  [GPU_FORMAT_ETC2_RGB8_UNORM]             = VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK,
  [GPU_FORMAT_ETC2_RGB8_UNORM_SRGB]        = VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK,
  [GPU_FORMAT_ETC2_RGB8A1_UNORM]           = VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK,
  [GPU_FORMAT_ETC2_RGB8A1_UNORM_SRGB]      = VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_4X4_UNORM]              = VK_FORMAT_ASTC_4x4_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_4X4_UNORM_SRGB]         = VK_FORMAT_ASTC_4x4_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_5X4_UNORM]              = VK_FORMAT_ASTC_5x4_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_5X4_UNORM_SRGB]         = VK_FORMAT_ASTC_5x4_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_5X5_UNORM]              = VK_FORMAT_ASTC_5x5_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_5X5_UNORM_SRGB]         = VK_FORMAT_ASTC_5x5_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_6X5_UNORM]              = VK_FORMAT_ASTC_6x5_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_6X5_UNORM_SRGB]         = VK_FORMAT_ASTC_6x5_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_6X6_UNORM]              = VK_FORMAT_ASTC_6x6_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_6X6_UNORM_SRGB]         = VK_FORMAT_ASTC_6x6_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_8X5_UNORM]              = VK_FORMAT_ASTC_8x5_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_8X5_UNORM_SRGB]         = VK_FORMAT_ASTC_8x5_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_8X6_UNORM]              = VK_FORMAT_ASTC_8x6_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_8X6_UNORM_SRGB]         = VK_FORMAT_ASTC_8x6_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_8X8_UNORM]              = VK_FORMAT_ASTC_8x8_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_8X8_UNORM_SRGB]         = VK_FORMAT_ASTC_8x8_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_10X5_UNORM]             = VK_FORMAT_ASTC_10x5_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_10X5_UNORM_SRGB]        = VK_FORMAT_ASTC_10x5_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_10X6_UNORM]             = VK_FORMAT_ASTC_10x6_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_10X6_UNORM_SRGB]        = VK_FORMAT_ASTC_10x6_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_10X8_UNORM]             = VK_FORMAT_ASTC_10x8_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_10X8_UNORM_SRGB]        = VK_FORMAT_ASTC_10x8_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_10X10_UNORM]            = VK_FORMAT_ASTC_10x10_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_10X10_UNORM_SRGB]       = VK_FORMAT_ASTC_10x10_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_12X10_UNORM]            = VK_FORMAT_ASTC_12x10_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_12X10_UNORM_SRGB]       = VK_FORMAT_ASTC_12x10_SRGB_BLOCK,
  [GPU_FORMAT_ASTC_12X12_UNORM]            = VK_FORMAT_ASTC_12x12_UNORM_BLOCK,
  [GPU_FORMAT_ASTC_12X12_UNORM_SRGB]       = VK_FORMAT_ASTC_12x12_SRGB_BLOCK,
  [GPU_FORMAT_DEPTH16_UNORM]               = VK_FORMAT_D16_UNORM,
  [GPU_FORMAT_STENCIL8]                    = VK_FORMAT_S8_UINT,
  [GPU_FORMAT_DEPTH24_UNORM_STENCIL8]      = VK_FORMAT_D24_UNORM_S8_UINT,
  [GPU_FORMAT_DEPTH32_FLOAT]               = VK_FORMAT_D32_SFLOAT,
  [GPU_FORMAT_DEPTH32_FLOAT_STENCIL8]      = VK_FORMAT_D32_SFLOAT_S8_UINT
};

GPU_HIDE
bool
vk_formatFromGPU(GPUFormat format, VkFormat *outFormat) {
  VkFormat native;

  if (!outFormat || format <= GPU_FORMAT_UNDEFINED ||
      format >= GPU_FORMAT_COUNT) {
    return false;
  }

  native = vk_formats[format];
  if (native == VK_FORMAT_UNDEFINED) {
    return false;
  }

  *outFormat = native;
  return true;
}

GPU_HIDE
GPUFormat
vk_formatToGPU(VkFormat format) {
  for (uint32_t i = 1u; i < GPU_FORMAT_COUNT; i++) {
    if (vk_formats[i] == format) {
      return (GPUFormat)i;
    }
  }
  return GPU_FORMAT_UNDEFINED;
}
