/*
 * Copyright (C) 2020 Recep Aslantas
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef gpu_format_h
#define gpu_format_h
#ifdef __cplusplus
extern "C" {
#endif

/* Backend-neutral; query adapter support before optional format use. */
typedef enum GPUFormat {
  GPU_FORMAT_UNDEFINED = 0,

  GPU_FORMAT_R8_UNORM,
  GPU_FORMAT_R8_SNORM,
  GPU_FORMAT_R8_UINT,
  GPU_FORMAT_R8_SINT,

  GPU_FORMAT_R16_UNORM,
  GPU_FORMAT_R16_SNORM,
  GPU_FORMAT_R16_UINT,
  GPU_FORMAT_R16_SINT,
  GPU_FORMAT_R16_FLOAT,

  GPU_FORMAT_RG8_UNORM,
  GPU_FORMAT_RG8_SNORM,
  GPU_FORMAT_RG8_UINT,
  GPU_FORMAT_RG8_SINT,

  GPU_FORMAT_R32_UINT,
  GPU_FORMAT_R32_SINT,
  GPU_FORMAT_R32_FLOAT,

  GPU_FORMAT_RG16_UNORM,
  GPU_FORMAT_RG16_SNORM,
  GPU_FORMAT_RG16_UINT,
  GPU_FORMAT_RG16_SINT,
  GPU_FORMAT_RG16_FLOAT,

  GPU_FORMAT_RGBA8_UNORM,
  GPU_FORMAT_RGBA8_UNORM_SRGB,
  GPU_FORMAT_RGBA8_SNORM,
  GPU_FORMAT_RGBA8_UINT,
  GPU_FORMAT_RGBA8_SINT,
  GPU_FORMAT_BGRA8_UNORM,
  GPU_FORMAT_BGRA8_UNORM_SRGB,

  GPU_FORMAT_RGB10A2_UNORM,
  GPU_FORMAT_RGB10A2_UINT,
  GPU_FORMAT_RG11B10_UFLOAT,
  GPU_FORMAT_RGB9E5_UFLOAT,

  GPU_FORMAT_RG32_UINT,
  GPU_FORMAT_RG32_SINT,
  GPU_FORMAT_RG32_FLOAT,

  GPU_FORMAT_RGBA16_UNORM,
  GPU_FORMAT_RGBA16_SNORM,
  GPU_FORMAT_RGBA16_UINT,
  GPU_FORMAT_RGBA16_SINT,
  GPU_FORMAT_RGBA16_FLOAT,

  GPU_FORMAT_RGBA32_UINT,
  GPU_FORMAT_RGBA32_SINT,
  GPU_FORMAT_RGBA32_FLOAT,

  GPU_FORMAT_BC1_RGBA_UNORM,
  GPU_FORMAT_BC1_RGBA_UNORM_SRGB,
  GPU_FORMAT_BC2_RGBA_UNORM,
  GPU_FORMAT_BC2_RGBA_UNORM_SRGB,
  GPU_FORMAT_BC3_RGBA_UNORM,
  GPU_FORMAT_BC3_RGBA_UNORM_SRGB,
  GPU_FORMAT_BC4_R_UNORM,
  GPU_FORMAT_BC4_R_SNORM,
  GPU_FORMAT_BC5_RG_UNORM,
  GPU_FORMAT_BC5_RG_SNORM,
  GPU_FORMAT_BC6H_RGB_FLOAT,
  GPU_FORMAT_BC6H_RGB_UFLOAT,
  GPU_FORMAT_BC7_RGBA_UNORM,
  GPU_FORMAT_BC7_RGBA_UNORM_SRGB,

  GPU_FORMAT_EAC_R11_UNORM,
  GPU_FORMAT_EAC_R11_SNORM,
  GPU_FORMAT_EAC_RG11_UNORM,
  GPU_FORMAT_EAC_RG11_SNORM,
  GPU_FORMAT_ETC2_RGBA8_UNORM,
  GPU_FORMAT_ETC2_RGBA8_UNORM_SRGB,
  GPU_FORMAT_ETC2_RGB8_UNORM,
  GPU_FORMAT_ETC2_RGB8_UNORM_SRGB,
  GPU_FORMAT_ETC2_RGB8A1_UNORM,
  GPU_FORMAT_ETC2_RGB8A1_UNORM_SRGB,

  GPU_FORMAT_ASTC_4X4_UNORM,
  GPU_FORMAT_ASTC_4X4_UNORM_SRGB,
  GPU_FORMAT_ASTC_5X4_UNORM,
  GPU_FORMAT_ASTC_5X4_UNORM_SRGB,
  GPU_FORMAT_ASTC_5X5_UNORM,
  GPU_FORMAT_ASTC_5X5_UNORM_SRGB,
  GPU_FORMAT_ASTC_6X5_UNORM,
  GPU_FORMAT_ASTC_6X5_UNORM_SRGB,
  GPU_FORMAT_ASTC_6X6_UNORM,
  GPU_FORMAT_ASTC_6X6_UNORM_SRGB,
  GPU_FORMAT_ASTC_8X5_UNORM,
  GPU_FORMAT_ASTC_8X5_UNORM_SRGB,
  GPU_FORMAT_ASTC_8X6_UNORM,
  GPU_FORMAT_ASTC_8X6_UNORM_SRGB,
  GPU_FORMAT_ASTC_8X8_UNORM,
  GPU_FORMAT_ASTC_8X8_UNORM_SRGB,
  GPU_FORMAT_ASTC_10X5_UNORM,
  GPU_FORMAT_ASTC_10X5_UNORM_SRGB,
  GPU_FORMAT_ASTC_10X6_UNORM,
  GPU_FORMAT_ASTC_10X6_UNORM_SRGB,
  GPU_FORMAT_ASTC_10X8_UNORM,
  GPU_FORMAT_ASTC_10X8_UNORM_SRGB,
  GPU_FORMAT_ASTC_10X10_UNORM,
  GPU_FORMAT_ASTC_10X10_UNORM_SRGB,
  GPU_FORMAT_ASTC_12X10_UNORM,
  GPU_FORMAT_ASTC_12X10_UNORM_SRGB,
  GPU_FORMAT_ASTC_12X12_UNORM,
  GPU_FORMAT_ASTC_12X12_UNORM_SRGB,

  GPU_FORMAT_DEPTH16_UNORM,
  GPU_FORMAT_STENCIL8,
  GPU_FORMAT_DEPTH24_UNORM_STENCIL8,
  GPU_FORMAT_DEPTH32_FLOAT,
  GPU_FORMAT_DEPTH32_FLOAT_STENCIL8,

  GPU_FORMAT_COUNT
} GPUFormat;

#ifdef __cplusplus
}
#endif
#endif /* gpu_format_h */
