function(gpu_windows_target_arch outVar)
  set(targetArch "${CMAKE_GENERATOR_PLATFORM}")
  if(NOT targetArch)
    set(targetArch "${CMAKE_C_COMPILER_ARCHITECTURE_ID}")
  endif()
  if(NOT targetArch AND CMAKE_SIZEOF_VOID_P EQUAL 4)
    set(targetArch x86)
  endif()
  if(NOT targetArch)
    set(targetArch "${CMAKE_SYSTEM_PROCESSOR}")
  endif()

  string(TOLOWER "${targetArch}" targetArch)
  if(targetArch MATCHES "arm64|aarch64")
    set(targetArch arm64)
  elseif(targetArch MATCHES "x64|amd64|x86_64")
    set(targetArch x64)
  elseif(targetArch MATCHES "win32|x86|i[3-6]86")
    set(targetArch x86)
  else()
    message(FATAL_ERROR
      "Unsupported Windows target architecture: ${targetArch}")
  endif()

  set(${outVar} "${targetArch}" PARENT_SCOPE)
endfunction()
